name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Build the distribution
        run: uv build

      - name: Publish to PyPI
        run: uv publish
